numbers=[10,20,30,40]
print(numbers.remove(10))
print(numbers)
print(numbers.pop(1))
print(numbers)
number=[4,5,2,1,3,6,9]
number.sort()
print(number)
number.reverse()
print(number)
print(len(number))
